// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TennisAcademyApp.Data;

#nullable disable

namespace TennisAcademyApp.Data.Migrations
{
    [DbContext(typeof(TennisAcademyDbContext))]
    [Migration("20260523183804_AddProfilePictureToUser")]
    partial class AddProfilePictureToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastWheelSpinDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OperationTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Bag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Bag Identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Bag Brand in English");

                    b.Property<string>("BrandBg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Bag Brand in Bulgarian");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Bag Image");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Bag Model in English");

                    b.Property<string>("ModelBg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Bag Model in Bulgarian");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Bag Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Available in stock");

                    b.HasKey("Id");

                    b.ToTable("Bags", t =>
                        {
                            t.HasComment("Bags Shop");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Wilson",
                            BrandBg = "Уилсън",
                            ImageUrl = "https://cdn.media.amplience.net/i/sportinglife/25918789_0/Team-3-Pack-Tennis-Bag?$default$&fmt=auto&w=540&h=540",
                            Model = "Team 3-Pack",
                            ModelBg = "Тийм 3-Пак",
                            Price = 59.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Head",
                            BrandBg = "Хед",
                            ImageUrl = "https://media.strefatenisa.com.pl/public/media/20/c1/2b/1721072068/head-tour-team-6r-combi-black-mixed-1.jpg?ts=1745860751",
                            Model = "Tour Team 6R",
                            ModelBg = "Тур Тийм 6Р",
                            Price = 89.99m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Babolat",
                            BrandBg = "Баболат",
                            ImageUrl = "https://m.media-amazon.com/images/I/61vGrieRbCL._UF1000,1000_QL80_.jpg",
                            Model = "Pure Drive RHx6",
                            ModelBg = "Пюр Драйв Ер Ха х6",
                            Price = 99.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Yonex",
                            BrandBg = "Йонекс",
                            ImageUrl = "https://www.midwestracquetsports.com/images/xl/BAG92429BK.jpg?v=1",
                            Model = "Pro Series 9-Pack",
                            ModelBg = "Про Сериес 9-Пак",
                            Price = 129.99m,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.BagCart", b =>
                {
                    b.Property<int>("BagId")
                        .HasColumnType("integer")
                        .HasComment("Foreign Key of Bag");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasComment("Foreign Key of IdentityUser");

                    b.Property<bool>("IsGift")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Quantity of Bags in Cart");

                    b.HasKey("BagId", "UserId", "IsGift");

                    b.HasIndex("UserId");

                    b.ToTable("BagCart");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Ball", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Ball Identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ball Brand in English");

                    b.Property<string>("BrandBg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ball Brand in Bulgarian");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ball Image");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ball Model in English");

                    b.Property<string>("ModelBg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Ball Model in Bulgarian");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Ball Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Available in stock");

                    b.HasKey("Id");

                    b.ToTable("Balls", t =>
                        {
                            t.HasComment("Balls Shop");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Wilson",
                            BrandBg = "Уилсън",
                            ImageUrl = "https://m.media-amazon.com/images/I/715MEN61aPL._UF1000,1000_QL80_.jpg",
                            Model = "US Open Extra Duty",
                            ModelBg = "Ю Ес Оупън Екстра Дюти",
                            Price = 12.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Head",
                            BrandBg = "Хед",
                            ImageUrl = "https://cdn.sportdepot.bg/files/catalog/detail/570823_01.jpg",
                            Model = "Tour XT",
                            ModelBg = "Тур Екс Те",
                            Price = 11.49m,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dunlop",
                            BrandBg = "Дънлоп",
                            ImageUrl = "https://m.media-amazon.com/images/I/618MvroxyXL._UF1000,1000_QL80_.jpg",
                            Model = "ATP Championship",
                            ModelBg = "Ей Ти Пи Чемпиъншип",
                            Price = 10.99m,
                            Quantity = 40
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.BallCart", b =>
                {
                    b.Property<int>("BallId")
                        .HasColumnType("integer")
                        .HasComment("Foreign Key of Ball");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasComment("Foreign Key of IdentityUser");

                    b.Property<bool>("IsGift")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Quantity of Balls in Cart");

                    b.HasKey("BallId", "UserId", "IsGift");

                    b.HasIndex("UserId");

                    b.ToTable("BallCart", t =>
                        {
                            t.HasComment("Ball Cart");
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Coach", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CoachId"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DescriptionBg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameBg")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NationalityBg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasComment("Identity User Identifier linked to this coach");

                    b.HasKey("CoachId");

                    b.HasIndex("UserId");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            CoachId = 1,
                            Age = 38,
                            Description = "One of the greatest tennis players of all time, known for his clay court dominance.",
                            DescriptionBg = "Един от най-великите тенисисти на всички времена, известен с доминацията си на клей кортове.",
                            ImageUrl = "https://imageio.forbes.com/specials-images/imageserve/5ece8a5c938ec500060aae37/0x0.jpg?format=jpg&crop=2462,2460,x503,y156,safe&height=416&width=416&fit=bounds",
                            IsDeleted = false,
                            Name = "Rafael Nadal",
                            NameBg = "Рафаел Надал",
                            Nationality = "Spanish",
                            NationalityBg = "Испанец"
                        },
                        new
                        {
                            CoachId = 2,
                            Age = 43,
                            Description = "Swiss tennis legend with unmatched elegance and 20 Grand Slam titles.",
                            DescriptionBg = "Швейцарска тенис легенда с ненадмината елегантност и 20 титли от Големия шлем.",
                            ImageUrl = "https://a.espncdn.com/combiner/i?img=/i/headshots/tennis/players/full/425.png",
                            IsDeleted = false,
                            Name = "Roger Federer",
                            NameBg = "Роджър Федерер",
                            Nationality = "Swiss",
                            NationalityBg = "Швейцарец"
                        },
                        new
                        {
                            CoachId = 3,
                            Age = 37,
                            Description = "Serbian champion, known for his resilience and complete game.",
                            DescriptionBg = "Сръбски шампион, известен със своята издръжливост и комплексна игра.",
                            ImageUrl = "https://a.espncdn.com/i/headshots/tennis/players/full/296.png",
                            IsDeleted = false,
                            Name = "Novak Djokovic",
                            NameBg = "Новак Джокович",
                            Nationality = "Serbian",
                            NationalityBg = "Сърбин"
                        },
                        new
                        {
                            CoachId = 4,
                            Age = 55,
                            Description = "American icon who redefined tennis in the 90s with a colorful personality.",
                            DescriptionBg = "Американска икона, която предефинира тениса през 90-те години с колоритна идентичност.",
                            ImageUrl = "https://www.atptour.com/-/media/alias/player-headshot/A092",
                            IsDeleted = false,
                            Name = "Andre Agassi",
                            NameBg = "Андре Агаси",
                            Nationality = "American",
                            NationalityBg = "Американец"
                        },
                        new
                        {
                            CoachId = 5,
                            Age = 68,
                            Description = "Swedish legend with ice-cold nerves and six French Open titles.",
                            DescriptionBg = "Шведска легенда с ледени нерви и шест титли от Ролан Гарос.",
                            ImageUrl = "https://lavercup.com/wp-content/uploads/2022/12/figure-borg-2.png",
                            IsDeleted = false,
                            Name = "Björn Borg",
                            NameBg = "Бьорн Борг",
                            Nationality = "Swedish",
                            NationalityBg = "Швед"
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Racket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Racket Identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Racket Brand in English");

                    b.Property<string>("BrandBg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Racket Brand in Bulgarian");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Racket Image");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Racket Model in English");

                    b.Property<string>("ModelBg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Racket Model in Bulgarian");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Racket Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Available in stock");

                    b.HasKey("Id");

                    b.ToTable("Rackets", t =>
                        {
                            t.HasComment("Rackets Shop");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Wilson",
                            BrandBg = "Уилсън",
                            ImageUrl = "https://cdncloudcart.com/28710/products/images/134337/tenis-raketa-wilson-pro-staff-rf-97-v13-0-tns-fr-image_6358bfebb40a9_800x800.jpeg?1666760684",
                            Model = "Pro Staff 97",
                            ModelBg = "Про Стаф 97",
                            Price = 349.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Babolat",
                            BrandBg = "Баболат",
                            ImageUrl = "https://babolat.bg/image/cache/catalog/tennis/2024/rackets/101474/101474-Pure_Drive_98-136-1-Face_2-250x250.jpg",
                            Model = "Pure Drive",
                            ModelBg = "Пюр Драйв",
                            Price = 299.99m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Head",
                            BrandBg = "Хед",
                            ImageUrl = "https://i.sportisimo.com/products/images/1104/1104555/700x700/head-graphene-360-speed-mp_1.jpg",
                            Model = "Graphene 360+ Speed",
                            ModelBg = "Графен 360+ Спийд",
                            Price = 279.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Yonex",
                            BrandBg = "Йонекс",
                            ImageUrl = "https://us.yonex.com/cdn/shop/files/EZ0898_BlastBlue_5868.jpg?v=1739481973&width=1946",
                            Model = "Ezone 98",
                            ModelBg = "Езоун 98",
                            Price = 319.99m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Prince",
                            BrandBg = "Принс",
                            ImageUrl = "https://images.squarespace-cdn.com/content/v1/56e9b38c2b8dde820241b62d/1471886555425-JT9KKFKPOL4FNLAV9ZB0/r2.jpg",
                            Model = "Tour 100P",
                            ModelBg = "Тур 100П",
                            Price = 259.99m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Tecnifibre",
                            BrandBg = "Технифайбър",
                            ImageUrl = "https://www.tecnifibre.com/dw/image/v2/BHDN_PRD/on/demandware.static/-/Sites-tecnifibre-master-catalog/default/dwcf93310b/hi-res/T-FIGHT%202025/Packshots/305S/14FI305S5_04.jpg?sw=608&sh=608&sm=fit",
                            Model = "TFight 305",
                            ModelBg = "Т-Файт 305",
                            Price = 289.99m,
                            Quantity = 7
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.RacketCart", b =>
                {
                    b.Property<int>("RacketId")
                        .HasColumnType("integer")
                        .HasComment("Foreign Key of Racket");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasComment("Foreign Key of IdentityUser");

                    b.Property<bool>("IsGift")
                        .HasColumnType("boolean");

                    b.Property<int?>("BallId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Quantity of Rackets in Cart");

                    b.HasKey("RacketId", "UserId", "IsGift");

                    b.HasIndex("BallId");

                    b.HasIndex("UserId");

                    b.ToTable("RacketCart", t =>
                        {
                            t.HasComment("Racket Cart");
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Reservation Identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer")
                        .HasComment("Choosing a coach");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Date Select");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasComment("Duration of the session");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasComment("Player Notes in English");

                    b.Property<string>("NoteBg")
                        .HasColumnType("text")
                        .HasComment("Player Notes in Bulgarian");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Player Identifer");

                    b.Property<int>("SurfaceId")
                        .HasColumnType("integer")
                        .HasComment("Choosing a surface");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("integer")
                        .HasComment("Choosing a training type");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SurfaceId");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasComment("Player Reservations");
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Surface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Surface Identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Image of the surface");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Surface Name in English");

                    b.Property<string>("NameBg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Surface Name in Bulgarian");

                    b.HasKey("Id");

                    b.ToTable("Surfaces", t =>
                        {
                            t.HasComment("Tennis Academy Surfaces");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://www.edwardssports.co.uk/pub/media/magefan_blog/Clay_Tennis_Courts.jpg",
                            Name = "Clay",
                            NameBg = "Клей (Червен корт)"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://www.tennisnerd.net/wp-content/uploads/2024/06/grass-tennis.webp",
                            Name = "Grass",
                            NameBg = "Трева"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://asltenniscourts.com.au/wp-content/uploads/2021/03/AdobeStock_253105355-1024x683.jpeg",
                            Name = "Hard",
                            NameBg = "Твърда настилка (Хард корт)"
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionBg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TitleBg")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Annual spring tournament open for all non-professional male players. Format: Direct elimination.",
                            DescriptionBg = "Годишен пролетен турнир, отворен за всички непрофесионални играчи (мъже). Формат: Директна елиминация.",
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 40.00m,
                            IsDeleted = false,
                            MaxParticipants = 32,
                            StartDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spring Clay Court Open",
                            TitleBg = "Пролетен отворен шампионат на клей"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Special dynamic tournament for women. Beautiful trophies and sponsor prizes provided.",
                            DescriptionBg = "Специален динамичен турнир за жени. Осигурени са красиви трофеи и награди от спонсори.",
                            EndDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 35.00m,
                            IsDeleted = false,
                            MaxParticipants = 16,
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Academy Women's Cup",
                            TitleBg = "Купа на Академията за жени"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Tournament targeted at young talents up to 18 years old. Great opportunity to boost local ranking points.",
                            DescriptionBg = "Турнир, насочен към млади таланти до 18 години. Страхотна възможност за трупане на точки за местната ранглиста.",
                            EndDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 20.00m,
                            IsDeleted = false,
                            MaxParticipants = 24,
                            StartDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Junior Summer Slams",
                            TitleBg = "Младежки летен шлем"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Bring your partner and fight for the grand trophy. Fun and highly competitive atmosphere.",
                            DescriptionBg = "Доведете партньора си и се борете за голямия трофей. Забавна и силно конкурентна атмосфера.",
                            EndDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 50.00m,
                            IsDeleted = false,
                            MaxParticipants = 16,
                            StartDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midsummer Mixed Doubles",
                            TitleBg = "Летни Смесени Двойки"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Exclusively for players aged 45 and above. Hard court battles, tactical play, and great experience.",
                            DescriptionBg = "Ексклузивно за играчи на възраст 45 и повече години. Битки на твърди кортове, тактическа игра и страхотно изживяване.",
                            EndDate = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 45.00m,
                            IsDeleted = false,
                            MaxParticipants = 32,
                            StartDate = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Masters Veterans Tournament",
                            TitleBg = "Мастърс Турнир за Ветерани"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Perfect tournament for recreation players who want to try competitive tennis. Matches played after 18:00.",
                            DescriptionBg = "Перфектен турнир за любители, които искат да се пробват в състезателния тенис. Мачовете се играят след 18:00 часа.",
                            EndDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 30.00m,
                            IsDeleted = false,
                            MaxParticipants = 64,
                            StartDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Weekend Warrior Amateur League",
                            TitleBg = "Лига 'Уикенд Воини' за Аматьори"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Experience the thrill of playing under the lights. Evening matches on fast hard courts.",
                            DescriptionBg = "Изживейте тръпката от играта под светлините на прожекторите. Вечерни мачове на бързи твърди кортове.",
                            EndDate = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 55.00m,
                            IsDeleted = false,
                            MaxParticipants = 32,
                            StartDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "August Night Hardcourt Championship",
                            TitleBg = "Августовски Нощен Шампионат"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Gathering the best local female players for an end-of-season showdown on clay.",
                            DescriptionBg = "Събиране на най-добрите местни тенисистки за сблъсък в края на сезона на клей корт.",
                            EndDate = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 35.00m,
                            IsDeleted = false,
                            MaxParticipants = 16,
                            StartDate = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Autumn Women Single Open",
                            TitleBg = "Есенен Отворен Шампионат за Жени"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "An exciting singles tournament for juniors to celebrate the new school season. Lots of prizes.",
                            DescriptionBg = "Вълнуващ сингъл турнир за юноши по случай новия учебен сезон. Множество награди.",
                            EndDate = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 15.00m,
                            IsDeleted = false,
                            MaxParticipants = 32,
                            StartDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Back to School Youth Cup",
                            TitleBg = "Младежка Купа 'Обратно на Училище'"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "The ultimate team tournament before moving to indoor courts. Group phase followed by eliminations.",
                            DescriptionBg = "Финалният отборен турнир преди преместването в закрити кортове. Групова фаза, последвана от елиминации.",
                            EndDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 60.00m,
                            IsDeleted = false,
                            MaxParticipants = 16,
                            StartDate = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Golden Autumn Doubles",
                            TitleBg = "Златна Есен Смесени Двойки"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "The first grand tournament of the winter season inside the academy’s premium heated halls.",
                            DescriptionBg = "Първият голям турнир за зимния сезон вътре в премиум отопляемите зали на академията.",
                            EndDate = new DateTime(2026, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 50.00m,
                            IsDeleted = false,
                            MaxParticipants = 32,
                            StartDate = new DateTime(2026, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Indoor Premium Cup",
                            TitleBg = "Закрит Премиум Шампионат"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Description = "Winter edition of our highly anticipated veteran tournament. Keep the competitive spirit alive.",
                            DescriptionBg = "Зимно издание на нашия дългоочакван ветерански турнир. Поддържайте състезателния дух жив.",
                            EndDate = new DateTime(2026, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 45.00m,
                            IsDeleted = false,
                            MaxParticipants = 16,
                            StartDate = new DateTime(2026, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Legends 45+ Winter Trophy",
                            TitleBg = "Зимна Трофейна Лига за Легенди 45+"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            Description = "Our final event of the year. All entry fees will be donated to local youth sports development.",
                            DescriptionBg = "Последното ни събитие за годината. Всички такси за участие ще бъдат дарени за развитието на местния младежки спорт.",
                            EndDate = new DateTime(2026, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 40.00m,
                            IsDeleted = false,
                            MaxParticipants = 64,
                            StartDate = new DateTime(2026, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Christmas Academy Charity Slams",
                            TitleBg = "Коледен Благотворителен Шлем на Академията"
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.TournamentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameBg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TournamentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Singles Men",
                            NameBg = "Сингъл Мъже"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Singles Women",
                            NameBg = "Сингъл Жени"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Juniors",
                            NameBg = "Юноши"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Doubles Mixed",
                            NameBg = "Смесени Двойки"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Veterans 45+",
                            NameBg = "Ветерани 45+"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Amateur League",
                            NameBg = "Аматьорска Лига"
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.TournamentUser", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TournamentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TournamentsUsers");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Training Type Identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Training Type Name in English");

                    b.Property<string>("NameBg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Training Type Name in Bulgarian");

                    b.HasKey("Id");

                    b.ToTable("Trainings", t =>
                        {
                            t.HasComment("Tennis Academy Trainings");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Physical Conditioning Routine",
                            NameBg = "Физическа подготовка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Technical Skill Development",
                            NameBg = "Развитие на технически умения"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tactical Game Strategy",
                            NameBg = "Тактическа стратегия за игра"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mental Toughness Training",
                            NameBg = "Психологическа устойчивост и ментална тренировка"
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.UserFavourite", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasComment("Foreign Key which references to IdentityUser");

                    b.Property<int>("CoachId")
                        .HasColumnType("integer")
                        .HasComment("Foreign Key which references to Coach");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "CoachId");

                    b.HasIndex("CoachId");

                    b.ToTable("UserFavourites", t =>
                        {
                            t.HasComment("Users Favourite Coach");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.BagCart", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Bag", "Bag")
                        .WithMany("BagCarts")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.BallCart", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Ball", "Ball")
                        .WithMany()
                        .HasForeignKey("BallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ball");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Coach", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.RacketCart", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Ball", null)
                        .WithMany("RacketCarts")
                        .HasForeignKey("BallId");

                    b.HasOne("TennisAcademyApp.Data.Models.Racket", "Racket")
                        .WithMany("RacketCart")
                        .HasForeignKey("RacketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Racket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Reservation", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Coach", "Coach")
                        .WithMany("Reservations")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.Surface", "Surface")
                        .WithMany("Reservations")
                        .HasForeignKey("SurfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.TrainingType", "TrainingType")
                        .WithMany("Reservations")
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Player");

                    b.Navigation("Surface");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Tournament", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.TournamentCategory", "Category")
                        .WithMany("Tournaments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.TournamentUser", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Tournament", "Tournament")
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.UserFavourite", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Coach", "Coach")
                        .WithMany("UserFavourites")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Bag", b =>
                {
                    b.Navigation("BagCarts");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Ball", b =>
                {
                    b.Navigation("RacketCarts");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Coach", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("UserFavourites");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Racket", b =>
                {
                    b.Navigation("RacketCart");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Surface", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Tournament", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.TournamentCategory", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.TrainingType", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
